### ISSUE TITLE
Stop service a lot and see this log 

### ISSUE THREAD

**Issue by ghost** [gawindx/homebridge-risco-platform#21]
![C05DB90B-26A6-4E99-BC88-D33FAF126C22](https://user-images.githubusercontent.com/67391365/96885143-fc8be100-148a-11eb-9c19-4263359880bb.png)
![Uploading 2B3EB395-19A1-4D1D-A411-4E143FB1EB7B.png…]()

**Comment by gawindx** [comment]
um ...
you are the second today to report a similar problem to me

so, either risco made a modification / maintenance or other, or there is a bug in the parse of the json but which does not affect everyone (no problem on my side and I also use different partitions).

I will inspect this but not before I get home and will give a better opinion in a few hours.

**Comment by ghost** [comment]
Thanks

**Comment by gawindx** [comment]
I think I fixed the problem, and it looks like it came from my code.

Can you test by getting the "Risco.js" file from the git to test before the patch is released?

**Comment by ghost** [comment]
I'd be happy,
Is this possible through HOOBS?

**Comment by gawindx** [comment]
I don't know HOOBS, I use homebridge in container or from an Ubuntu VM for the dev.

In principle, HOOBS is under linux so a connection in ssh to have access to the Linux console.
Then go to the plugin directory:
`cd /home/hoobs/.hoobs/node-modules/homebridge-risco-platform`
and finally :
`wget https://raw.githubusercontent.com/gawindx/homebridge-risco-platform/master/Risco.js`

provided that wget is installed by default.

i think that should do it

**Comment by gawindx** [comment]
version 1.1.7 must correct the problem, in addition to some improvements (not visual, so no change on the service side or other)

**Comment by gawindx** [comment]
Can you confirm to me that the last version corrected the problem?

**Comment by ghost** [comment]
<img width="1670" alt="צילום מסך 2020-10-30 ב-19 17 09" src="https://user-images.githubusercontent.com/67391365/97736673-b9fa8200-1ae4-11eb-90a0-f7982cf1fd23.png">
Hi,
its from now, the service is work easy after this logs and after reset its start to work well (every time) [sorry about my English]
if do you want me to test new version tell me I work now with home bridge instead hoobs.
thanks!

**Comment by gawindx** [comment]
The latest version is 1.1.7, is this the one you have installed?

**Comment by gawindx** [comment]
can you also show me your config (without your login of course)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/67391365/97740002-45761200-1ae9-11eb-885e-2fb017254ede.jpeg)
![image](https://user-images.githubusercontent.com/67391365/97740014-49099900-1ae9-11eb-998c-11c22e4b4a55.jpeg)

**Comment by gawindx** [comment]
I understood where the problem comes from, you only use the partitions and not the detectors, which explains the error.

I will correct the code to take this scenario into account.

There are no obligations to define the detectors but in my logic I did not take them into account

**Comment by ghost** [comment]
Okay :) 
What does it actually give me if I set the detectors?

**Comment by gawindx** [comment]
This allows visual feedback from the detectors (knowing if movement is detected on a particular sensor), as well as the possibility of excluding them directly from homekit (recent function).

As the Home application allows you to configure notifications on the activation of a particular accessory, you can receive a notification when the sensor is activated.

Provided that you have a hub that allows you to manage homekit outside the local network:
For example, you can receive a notification when a door is opened, whether your system is armed or not.

On the other hand, depending on the riscocloud, there can sometimes be a delay between the activation of the sensor and the notification of the movement.

**Comment by gawindx** [comment]
I just pushed an update to the plugin.

Contrary to what I thought, this case was well taken into account and it works perfectly on my end whether or not I set the detectors to "none".

I still made a small edit which I hope will solve your problem.

**Comment by gawindx** [comment]
It will not solve your problem, I badly analyze the error.

**Comment by gawindx** [comment]
version 1.1.9 should work better, you can update.

I was able to reproduce the problem and correct it.

**Comment by ghost** [comment]
I just updated.  Thank you very much for your patience and response.  If anything still appears to me.  I will update you.

**Comment by andyblac** [comment]
this update has broken my alarm, it now will not set or unset. nothing in logs,

**Comment by andyblac** [comment]
Just say arming....  or disarming....  then after few mins tiles just revert to how it was

**Comment by gawindx** [comment]
Sorry for the inconvenience
I will do some tests tomorrow to see if I encounter the same problems as you and correct all this quickly

**Comment by andyblac** [comment]
> Sorry for the inconvenience
> I will do some tests tomorrow to see if I encounter the same problems as you and correct all this quickly

Np thanks I’ll use old file from git in the mean time

**Comment by andyblac** [comment]
Just let you know if I set on panel it reports correctly in homekit

**Comment by gawindx** [comment]
I think the problem is solved.
The problem came from a syntax error when improving support for ES6, not changes for the issue encountered by @barack65

**Comment by andyblac** [comment]
> I think the problem is solved.
> The problem came from a syntax error when improving support for ES6, not changes for the issue encountered by @barack65

ok, i'll test update and report back

**Comment by andyblac** [comment]
yup 1.1.10 fixes it thanks, sorry for hijacking this ticket.

**Comment by gawindx** [comment]
no problem, the weapon issue was indirectly linked to this issue and the update correcting it, so that doesn't shock me.

I think I can close the issue
